---
all:
  hosts:
  children:
    api:
      hosts:
        api-server:
  vars:
    # change this to actual username for remote ssh access
    # ansible_user: admin

    # change this to actual ssh key or using ssh_config
    # ansible_ssh_private_key_file=/path/to/private_key
