- name: 'deploy api service'
  hosts: api
  tasks:
  - name: 'install python3-docker'
    # python3-docker is needed for docker container management via ansible
    ansible.builtin.package:
      name: ['python3-docker']
      state: present
  # NOTE: uncomment these lines if using private registry
  # - name: 'login to registry'
  #   ansible.builtin.docker_login:
  #     registry: '{{ docker_registry }}'
  #     username: '{{ docker_registry_username }}'
  #     password: '{{ docker_registry_password }}'
  #     reauthorize: yes
  - name: 'update docker container image'
    ansible.builtin.docker_container:
      name: 'webapi'
      state: started
      pull: true
      recreate: true
      image: '{{ docker_image }}'
      # NOTE: here port forwarding is for nginx, demonstrating purpose
      ports:
      - 3000:80
      env:
        DB_URL: '{{ db_url }}'
        DB_USERNAME: '{{ db_username }}'
        DB_PASSWORD: '{{ db_password }}'
