---
# initialize for api server
- hosts: api
  tasks:
  - name: 'example'
    ansible.builtin.shell: 'date'
  - name: 'install docker'
    ansible.builtin.package:
      name: ['docker']
      state: present
  # NOTE: docker basic configuration file, like storage-driver, registry-mirrors
  - name: 'install nginx'
    ansible.builtin.package:
      name: ['nginx']
      state: present
  - name: 'upload basic nginx config'
# initialize for database server
- hosts: api
  tasks:
  - name: 'example'
    shell: 'date'
  - name: 'install mysql'
    ansible.builtin.package:
      name: 'mariadb'
      state: present
