---
# initialize for api server
- hosts: api
  tasks:
  - name: 'example'
    ansible.builtin.shell: 'date'
  - name: 'install docker'
    ansible.builtin.package:
      name: ['docker.io']
      state: present
# - name: 'upload docker config'
#   ansible.builtin.:

  # NOTE: docker basic configuration file, like storage-driver, registry-mirrors
  - name: 'install nginx'
    ansible.builtin.package:
      name: ['nginx']
      state: present
# initialize for database server
- hosts: api
  tasks:
  - name: 'example'
    shell: 'date'
  - name: 'install mysql'
    ansible.builtin.package:
      name: 'mariadb'
      state: present
