---
apiVersion: v1
data:
  nginx-site.conf: |
    # -*- mode: nginx -*-
    server {
      listen 3000 default;
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }
    }
kind: ConfigMap
metadata:
  name: api-site
