---
apiVersion: v1
data:
  password: ZGVtb3BAc3N3b3Jk
  root_password: cm9vdHBAc3N3b3Jk
  username: ZGVtbw==
kind: Secret
metadata:
  name: mysql
type: Opaque

---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJteS1yZWdpc3RyeS5leGFtcGxlOjUwMDAiOnsidXNlcm5hbWUiOiJ0aWdlciIsInBhc3N3b3JkIjoicGFzczExMyIsImVtYWlsIjoidGlnZXJAYWNtZS5jb20iLCJhdXRoIjoiZEdsblpYSTZjR0Z6Y3pFeE13PT0ifX19
kind: Secret
metadata:
  name: docker
type: kubernetes.io/dockerconfigjson
