# -*- mode: yaml -*-
---
all:
  hosts:
  children:
    api:
      hosts:
        api-server:
      vars:
        # NOTE change this to actual image like registry.wcl.com/wcl/api:latest
        docker_image: nginx:alpine
        # NOTE change this to actual image like registry.wcl.com
        docker_registry: docker.io
    db:
      hosts:
        db-server:
      vars:
        db_name: wiredcraft_task
        dump_path: /tmp/
