name: unittest-workflow
on:
  pull_request: {}
  workflow_dispatch: {} # manually
  # push: {}
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    steps:
    - name: checkout code repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: create virtualenv, then setup environment
      working-directory: 004-docker-and-a-bit-of-dev/python
      env:
        PIPENV_VENV_IN_PROJECT: 1
      run: |
        python -m venv .venv
        .venv/bin/pip install pipenv
        .venv/bin/pipenv install -d
    - name: run unittest
      working-directory: 004-docker-and-a-bit-of-dev/python
      run: .venv/bin/pytest test.py
